name: reviewdog
on:
  pull_request:
    branches:
      - develop

jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          fail_on_error: true
          reporter: github-pr-review
          stylelint_input: './src/**/*.{css,pcss}'

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-eslint@v1
        with:
          level: error
          fail_on_error: true
          reporter: github-pr-review
          eslint_flags: '. --ext .ts,.tsx --quiet'

  tests:
    name: runner / test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          test-script: npm run test:ci -- --outputFile=report.json
          output: comment, report-markdown
          skip-step: none
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
